### ISSUE TITLE
a few bugs in the compression

### ISSUE THREAD

**Issue by thenumbernine** [dansgithubuser/dansSuperMetroidLibrary#1]
Hello there,
I (cited and) borrowed heavily from your Super Metroid compression functions for a project of my own, and tested the implementations by decompressing, recompressing, decompressing, and comparing all the data of the original ROM's rooms.
I found a few bugs that you might be interested in:
1) sm.cpp:284, a no-compress block can possibly surpass the MAX_BLOCK_LENGTH. To fix this I just added a '|| noCompressionLength == MAX_BLOCK_LENGTH' into the if-condition, and 'noCompressionLength = 0' inside the if statement's block, after the 'noCompress' call.
2) sm.cpp:235, I found cases where bestLength was zero.  The next line will call 'putBlockHeader' with a zero length, which then tries to write an op with a 'length+1' value of -1, which translates to 0xff.  In the case that it is writing LZ op 7 this will produce an extended command with an upper byte of 0xff, which can be seen as a terminator in the decompressor. To fix this I just added a line after 'if (length==0) return;' after line 235, before the call to 'putBlockHeader'.
3) sm.cpp:49, MAX_BLOCK_LENGTH=1024, which is represented in an extended cmd as 111xxx11:1111:1111b, however if the cmd itself is LZ op 7 then we get a 0xff for the first byte, which is interpreted as a terminator.  I worked around this by setting my MAX_BLOCK_LENGTH to 10:1111:1111b = 767.
I picked up the last two by adding the line 'assert(length >= 1 && length <= MAX_BLOCK_LENGTH) after line 120.

**Comment by dansgithubuser** [comment]
@thenumbernine how does PR https://github.com/dansgithubuser/dansSuperMetroidLibrary/pull/2 look?

**Comment by thenumbernine** [comment]
Looks great, awesome.  Good call on only lowering the max block size for LZ op 7, since that's the only case that it can cause the extended cmd to have 0xff as the first byte.
